baseurl: '/'
title: Flatcar Container Linux
canonifyurls: true
paginate: 8
theme: flatcar
languageCode: en-us
copyright: Copyright the Flatcar Project Contributors
pluralizelisttitles: 'false'
permalinks:
  blog: "/blog/:year/:month/:title/"

params:
  news_stripe:
    text: 'Join our <a href="https://github.com/flatcar-linux/Flatcar/#monthly-community-meeting-and-release-planning">community calls</a>, every second Tuesday of each month at 4:30 GMT.'
    expiration: "2023-12-29T17:00:00+02:00"
    style:
      bgcolor: ""
      fgcolor: ""
  DateForm: 'Jan 2, 2006'
  Description: Flatcar Container Linux website
  Author: Chris Kuehl
  Email: hello@kinvolk.io
  Subtitle: Linux for containers
  social:
    - title: twitter
      url: 'https://twitter.com/flatcar'
      image: 'twitter-icon'
    - title: github
      url: 'https://github.com/flatcar-linux'
      image: 'github-icon'
  favicon: "/media/brand-logo.svg"
  docs:
    github_edit_url: https://github.com/flatcar-linux/flatcar-docs/edit/main/docs/
    issues_url: https://github.com/kinvolk/flatcar/issues/new?labels=kind/docs
    external_docs:
    - repo: https://github.com/flatcar-linux/flatcar-docs.git
      name: "latest"
      branch: "main"
      dir: "docs"


pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: "vs"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

assetDir: static

outputs:
  home:
  - json
  - html

privacy:
  youtube:
    privacyEnhanced: true

menu:
  main:
    - name: FAQ
      url: /faq
      identifier: faq
      weight: -100
    - name: Security
      url: /security
      identifier: security
      weight: -50
    - name: Blog
      url: /blog
      identifier: blog
      weight: -500
    - name: Releases
      url: /releases
      identifier: releases
      weight: -400
    - name: Docs
      url: /docs
      identifier: docs
      weight: -200

