baseurl: '/'
title: Flatcar Linux
canonifyurls: true
paginate: 8
theme: flatcar
languageCode: en-us
copyright: © 2018 Kinvolk GmbH
pluralizelisttitles: 'false'
author:
  name: Chris Kuehl
params:
  DateForm: 'Jan 2, 2006'
  Description: Flatcar Linux website
  Author: Chris Kuehl
  Email: hello@kinvolk.io
  Subtitle: Linux for containers
  social:
    - title: twitter
      url: 'https://twitter.com/flatcar_linux'