[build]
publish = "public"
command = "make"

[context.production.environment]
GO_VERSION = "1.12"
HUGO_VERSION = "0.83.1"
PYTHON_VERSION = "3.7"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "make build-preview"

[context.deploy-preview.environment]
GO_VERSION = "1.12"
HUGO_VERSION = "0.83.1"
PYTHON_VERSION = "3.7"
NETLIFY_BUILD_PREVIEW = "true"
