# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Flatcar Linux Theme"
license = "All rights reserved"
description = "Flatcar Linux - Linux for containers"
homepage = "https://flatcar-linux.org"
tags = ["project", "landing-page"]
features = ["", ""]
min_version = 0.36

[author]
  name = "Chris Kuehl"
  homepage = "flatcar-linux.org"
