name: Trigger Kinvolk website build
on:
  push:
    branches:
    - master
    paths:
    - ./content/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/kinvolk/website/actions/workflows/update-blogs.yml/dispatches \
          -d '{"ref": "master"}'
